routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('driver', 'DriverController');

app/Driver.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Collective\Html\Eloquent\FormAccessible;

class Driver extends Model
{
    //use FormAccessible;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name',
        'email', 'phone',
        'address_1', 'address_2', 'address_3',
        'postal_code', 'city', 'country',
    ];

    protected $with = [
        'driverLicense',
    ];

    public function driverLicense()
    {
        return $this->hasOne(DriverLicense::class);
    }

    public function getNameAttribute()
    {
        return sprintf('%s %s', $this->first_name, $this->last_name);
    }

    public function getAddressAttribute()
    {
        $pattern = $this->address_3 ? '%s %s/%s' : '%s %s';

        return sprintf($pattern, $this->address_1, $this->address_2, $this->address_3);
    }
}

app/DriverLicense.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DriverLicense extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'number',
        'category',
        'valid_from', 'valid_to',
    ];

    public function driver()
    {
        return $this->belongsTo(Driver::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DriverController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DriverRequest;
use App\Traits\HasDriverCategories;
use App\DriverLicense;
use App\Driver;

class DriverController extends Controller
{
    use HasDriverCategories;

    public function index()
    {
        $drivers = Driver::paginate();

        return view('driver.index', [
            'drivers' => $drivers,
        ]);
    }

    public function create()
    {
        $categories = $this->getDriverCategories();

        return view('driver.create', [
            'categories' => $categories,
        ]);
    }

    public function store(DriverRequest $request)
    {
        $driver = Driver::create($request->input('driver'));
        $driver->driverLicense()->create($request->input('license'));

        return redirect()->route('driver.index')->withFlash('Pomyślnie dodano kierowcę');
    }

    public function show(Driver $driver)
    {
        return view('driver.show', [
            'driver' => $driver,
        ]);
    }

    public function edit(Driver $driver)
    {
        $categories = $this->getDriverCategories();

        return view('driver.edit', [
            'driver'     => $driver,
            'categories' => $categories,
        ]);
    }

    public function update(DriverRequest $request, Driver $driver)
    {
        $driver->update($request->input('driver'));
        $driver->driverLicense->update($request->input('license'));

        return redirect()->route('driver.index')->withFlash('Pomyślnie zaktualizowano kierowcę');
    }

    public function destroy(Driver $driver)
    {
        $driver->delete();

        return redirect()->route('driver.index')->withFlash('Pomyślnie usunięto kierowcę');
    }
}

resources/views/driver/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('driver.create') }}
    {{ Form::open(['route' => 'driver.store']) }}
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <h3>Kierowca</h3>
                        @include('driver.inputs.driver', [
                            'driver' => new App\Driver,
                        ])
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card">
                    <div class="card-body">
                        <h3>Prawo jazdy</h3>
                        @include('driver.inputs.license', [
                            'license' => new App\DriverLicense,
                        ])
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                @include('layouts.form-button', [
                    'text' => 'Dodaj »',
                ])
            </div>
        </div>
    {{ Form::close() }}
</div>
@endsection

resources/views/driver/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('driver.edit', $driver) }}
    {{ Form::model($driver, ['route' => ['driver.update', $driver], 'method' => 'PUT']) }}
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <h3>Kierowca</h3>
                        @include('driver.inputs.driver')
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card">
                    <div class="card-body">
                        <h3>Prawo jazdy</h3>
                        @include('driver.inputs.license', [
                            'license' => $driver->driverLicense,
                        ])
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                @include('layouts.form-button', [
                    'text' => 'Edytuj »',
                ])
            </div>
        </div>
    {{ Form::close() }}
</div>
@endsection

resources/views/driver/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('driver.index') }}
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="offset-md-4 col-md-4 col-12">
                    <a class="btn btn-success btn-block" href="{{ route('driver.create') }}">Dodaj nowego kierowcę</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover table-responsive">
                <thead>
                    <tr>
                        <th>Lp.</th>
                        <th>Imię i nazwisko</th>
                        <th>Numer telefonu</th>
                        <th>Adres e-mail</th>
                        <th class="col-1"></th>
                        <th class="col-1"></th>
                        <th class="col-1"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($drivers as $driver)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $driver->name }}</td>
                            <td>{{ $driver->phone }}</td>
                            <td>{{ $driver->email }}</td>
                            <td><a href="{{ route('driver.show', $driver) }}" class="btn btn-warning btn-block">Pokaż</a></td>
                            <td><a href="{{ route('driver.edit', $driver) }}" class="btn btn-primary btn-block">Edytuj</a></td>
                            <td><a href="{{ route('driver.destroy', $driver) }}" class="btn btn-danger btn-block">Usuń</a></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        {{ $drivers->links() }}
    </div>
</div>
@endsection

resources/views/driver/inputs/driver.blade.php
<div class="row">
    <div class="col-6">
        <div class="form-group">
            {{ Form::label('driver-first_name', 'Imię', ['class' => 'form-label']) }}
            {{ Form::text('driver[first_name]', $driver->first_name, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            {{ Form::label('driver-last_name', 'Nazwisko', ['class' => 'form-label']) }}
            {{ Form::text('driver[last_name]', $driver->last_name, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            {{ Form::label('driver-email', 'Adres e-mail', ['class' => 'form-label']) }}
            {{ Form::text('driver[email]', $driver->email, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            {{ Form::label('driver-phone', 'Numer telefonu', ['class' => 'form-label']) }}
            {{ Form::text('driver[phone]', $driver->phone, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            {{ Form::label('driver-address_1', 'Ulica', ['class' => 'form-label']) }}
            {{ Form::text('driver[address_1]', $driver->address_1, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-3">
        <div class="form-group">
            {{ Form::label('driver-address_2', 'Numer domu', ['class' => 'form-label']) }}
            {{ Form::text('driver[address_2]', $driver->address_2, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-3">
        <div class="form-group">
            {{ Form::label('driver-address_3', 'Numer lokalu', ['class' => 'form-label']) }}
            {{ Form::text('driver[address_3]', $driver->address_3, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-3">
        <div class="form-group">
            {{ Form::label('driver-postal_code', 'Kod pocztowy', ['class' => 'form-label']) }}
            {{ Form::text('driver[postal_code]', $driver->postal_code, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-3">
        <div class="form-group">
            {{ Form::label('city', 'Miasto', ['class' => 'form-label']) }}
            {{ Form::text('driver[city]', $driver->city, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            {{ Form::label('driver-country', 'Państwo', ['class' => 'form-label']) }}
            {{ Form::text('driver[country]', $driver->country ?: 'Polska', ['class' => 'form-control']) }}
        </div>
    </div>
</div>

resources/views/driver/inputs/license.blade.php
<div class="form-group">
    {{ Form::label('license-number', 'Numer', ['class' => 'form-label']) }}
    {{ Form::text('license[number]', $license->number, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('license-category', 'Kategoria', ['class' => 'form-label']) }}
    {{ Form::select('license[category]', $categories, $license->category, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('license-valid_from', 'Ważne od', ['class' => 'form-label']) }}
    {{ Form::date('license[valid_from]', $license->valid_from, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('license-valid_to', 'Ważne do', ['class' => 'form-label']) }}
    {{ Form::date('license[valid_to]', $license->valid_to, ['class' => 'form-control']) }}
</div>

resources/views/driver/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('driver.show', $driver) }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <table class="table table-striped table-hover table-responsive">
                        <tbody>
                            <tr>
                                <th width="1%" scope="row">Imię i nazwisko</th>
                                <td width="2%">{{ $driver->name }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Adres</th>
                                <td>
                                    {{ $driver->address }}<br/>
                                    {{ $driver->postal_code }} {{ $driver->city }} - {{ $driver->country }}
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">Kontakt</th>
                                <td>
                                    {{ $driver->phone }}<br/>
                                    {{ $driver->email }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-6">
                    <table class="table table-striped table-hover table-responsive">
                        <tbody>
                            <tr>
                                <th width="1%" scope="row">Numer prawa jazdy</th>
                                <td width="2%">{{ $driver->driverLicense->number }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Kategoria</th>
                                <td>{{ $driver->driverLicense->category }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Data ważności</th>
                                <td>
                                    {{ $driver->driverLicense->valid_from }} - {{ $driver->driverLicense->valid_to }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="offset-4 col-4">
                    <a class="btn btn-primary btn-block" href="{{ route('driver.edit', $driver) }}">Edytuj »</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        @yield('assets')
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Taxi</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"  aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('driver.index') }}">Kierowcy</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container text-center">
            @include('flash::message')
        </div>
        @include('layouts.error')
        @yield('content')
        <script src="{{ asset('js/app.js') }}" charset="utf-8"></script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        @stack('scripts')
    </body>
</html>

resources/views/layouts/error.blade.php
<div class="container text-center">
    @if (isset($errors) && $errors->count())
        <div class="alert alert-danger align-middle">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <ul class="list-unstyled">
                @foreach ($errors->all() as $error)
                    <li>{!! $error !!}</li>
                @endforeach
            </ul>
        </div>
    @endif
</div>

resources/views/layouts/form-button.blade.php
<div class="row">
    <div class="offset-4 col-4">
        {{ Form::button($text, [
            'class' => 'btn btn-success btn-block',
            'type'  => 'submit',
        ]) }}
    </div>
</div>